@startuml

title Klassendiagramm

class User
class Address
class Ingredient
class Recipe
class Comment
class Rating
class Favorites
class ShoppingList
enum Category
enum Unit

ShoppingList "1" -- "*" Ingredient

User "1" -- "*" ShoppingList

User "1" -- "0..1" Address
User "1" -- "*" Favorites
User "1" -- "*" Comment

Recipe "*" -- "*" Category
Recipe "1" -- "*" Comment
Rating "0..1" -- "1" Comment
Recipe "*" -- "1" User
Recipe "1" -- "1" Favorites

PreparationSteps "1" --* "1..*" Recipe: Conposition
Ingredient "*" --* "1..*" Recipe: Conposition

Unit "1" --o "*" Ingredient: Aggregation
Price "1" --o "1" Ingredient: Aggregation

class Price {
    -Number value
    -String currency
}

class Ingredient {
  -String name
  -String description
}

class Recipe {
  -String title
  -String description

  +createIndredient(): { name, desc, unit, price }
  +addIndredient(): { ingredient }
  +addStep(): { number, text }
  +addCategory():  { category }
  +addComment(){ text, rating }

  +addToFavorites()
  +addToShoppingList()

}

class PreparationSteps {
    -Number step
    -String text
}

class User {
  -String name
  -String surname
  -String email
}

class Rating {
  -Nummber rating
}

class Comment {
  -Rating rating
  -String text
}

class Favorites {
}

class ShoppingList {
}

@enduml
